# Don't print a new line at the start of the prompt
add_newline = false

format = "$all"


# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[directory]
truncate_to_repo = false

[username]
show_always = true